### ISSUE TITLE
参数未对齐

### ISSUE THREAD

**Issue by shanshuiguochu** [yfgeek/GithubFollow#2]
D:\>cd Python27

D:\Python27>python.exe github.py
Getting the authenticity_token
fW7QLXsW6vTvIE/Fzo2aBGTVLNirHssCfBcH/2Ws5++p54C94ShkVgijGi3h4Ka+R0rud3RzPSh/pkvk
443dlw==
Login Successful

In the page 100, following the NO.0 user: DenisDuan
Token：eM5sHL8PsmZ0+c75zLn9+OUZO/gWmLGDGu+/BY9gOVXgiy60AykLdM5/w8lGPA/HFib6FYzj8
Q4Re4ncdgG0Mw==
Retrying...
Traceback (most recent call last):
  File "github.py", line 143, in <module>
    gt.list_follow(i,'yfgeek') #复制列表的人 The person who you want to copy his
 follower to yours
  File "github.py", line 127, in list_follow
    self.__follow_user(tokenlist[i],userlist[i])
  File "github.py", line 101, in __follow_user
    self.__follow_user(self,token,username)
TypeError: __follow_user() takes exactly 3 arguments (4 given)

D:\Python27>python.exe github.py
Getting the authenticity_token
+x6P/Lp7z0B8/y3diMQspU23oXhsG+blWT8KgzYdpedUxo5IdN0UzaUKvW1XOirIXK+lMc3Cej2eC25O
bvfqpg==
Login Successful

In the page 100, following the NO.0 user: DenisDuan
Token：+JFV9fSwmtWA6eN+gPyt6t5KiGsy0K0j1b2EnHJiMgE2AX+z2VGSwP0aJUWUW9PLMV+HhI33k
/YNVDT2hq6Y/A==
Retrying...
Traceback (most recent call last):
  File "github.py", line 143, in <module>
    gt.list_follow(i,'yfgeek') #复制列表的人 The person who you want to copy his
 follower to yours
  File "github.py", line 127, in list_follow
    self.__follow_user(tokenlist[i],userlist[i])
  File "github.py", line 101, in __follow_user
    self.__follow_user(self,token,username)
TypeError: __follow_user() takes exactly 3 arguments (4 given)

**Comment by yfgeek** [comment]
感谢！
已修复。
```
git pull
```
仍有问题请继续在这个issuse下提问

**Comment by shanshuiguochu** [comment]
谢谢！
